package com.example.chatbot.ml

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

/**
 * Parity tests for [TextEncoder].
 *
 * The expected values here were generated by running the Python training
 * pipeline over the same vocabulary. If these fail, Kotlin and Python have
 * diverged and every prediction on device is silently wrong.
 */
class TextEncoderTest {

    private lateinit var words: List<String>
    private lateinit var encoder: TextEncoder

    private fun resource(name: String): String =
        javaClass.classLoader!!.getResourceAsStream(name)!!.bufferedReader().use { it.readText() }

    @Before
    fun setUp() {
        val arr = JSONArray(resource("words.json"))
        words = List(arr.length()) { arr.getString(it) }

        val lemmaJson = JSONObject(resource("lemmas.json"))
        val lemmas = lemmaJson.keys().asSequence().associateWith { lemmaJson.getString(it) }

        encoder = TextEncoder(words, lemmas)
    }

    // --- shape -------------------------------------------------------------

    @Test
    fun `encoded row is one slot per vocabulary word`() {
        assertEquals(272, encoder.vocabularySize)
        assertEquals(272, encoder.encode("hi").size)
    }

    // --- tokenising --------------------------------------------------------

    @Test
    fun `lowercases input`() {
        assertEquals(listOf("hello", "there"), encoder.tokenize("HELLO THERE"))
        assertEquals(listOf("hello", "there"), encoder.tokenize("hello there"))
    }

    @Test
    fun `strips punctuation`() {
        assertEquals(listOf("hi"), encoder.tokenize("hi!"))
        assertEquals(listOf("hi"), encoder.tokenize("...hi..."))
    }

    @Test
    fun `lemmatizes plurals using the exported lookup`() {
        assertEquals(listOf("book"), encoder.tokenize("books"))
        assertEquals(listOf("child"), encoder.tokenize("children"))
        // a word with no lemma entry passes through unchanged
        assertEquals(listOf("renew"), encoder.tokenize("renew"))
    }

    @Test
    fun `splits contractions the way NLTK does`() {
        // NLTK turns "don't" into ["do", "n't"] - the vocabulary contains "n't"
        assertTrue("n't" in encoder.tokenize("I don't have my card"))
        assertTrue("'re" in encoder.tokenize("you're not helping"))
        assertTrue("'ve" in encoder.tokenize("I've lost my card"))
        assertTrue("'s" in encoder.tokenize("What's the address?"))
    }

    @Test
    fun `drops empty tokens`() {
        assertTrue(encoder.tokenize("   ").isEmpty())
        assertTrue(encoder.tokenize("").isEmpty())
    }

    // --- parity with Python ------------------------------------------------

    /** Slots the Python pipeline sets for each sentence. Generated, not guessed. */
    private val pythonExpected = mapOf(
        "hi" to intArrayOf(112),
        "Can I renew my books?" to intArrayOf(36, 49, 122, 157, 199),
        "I don't have my card" to intArrayOf(50, 72, 104, 122, 157, 158),
        "you're not helping" to intArrayOf(1, 167, 269),
        "What's the address?" to intArrayOf(2, 12, 239, 255),
        "I've lost my card" to intArrayOf(3, 50, 122, 147, 157),
        "HELLO THERE" to intArrayOf(106, 240),
        "zzz qqq" to intArrayOf(),
    )

    @Test
    fun `encodes exactly the slots the Python pipeline does`() {
        for ((sentence, expected) in pythonExpected) {
            val actual = encoder.encode(sentence)
                .mapIndexed { i, v -> i to v }
                .filter { it.second == 1f }
                .map { it.first }
                .toIntArray()
            assertArrayEquals("mismatch for \"$sentence\"", expected, actual)
        }
    }

    @Test
    fun `unknown words produce an all-zero row`() {
        val row = encoder.encode("zzz qqq wibble")
        assertTrue("expected every slot to be 0", row.all { it == 0f })
    }

    @Test
    fun `known slot positions are stable`() {
        assertEquals("renew", words[199])
        assertEquals("heya", words[111])
    }
}
